### ISSUE TITLE
Update command line parameters syntax with the --name=value syntax

### ISSUE THREAD

**Issue by end2endzone** [end2endzone/bin2cpp#2]
Rename arguments fields:
* inputfile -> file
* output folder -> output
* header filename -> headerfile
* function identifier -> identifier
* chunk size -> chunksize

ie:
--file=/path/to/input/file
--output=/path/to/output/folder
--headerfile=SplashScreen.h
--identifier=SplashScreen
--chunksize=200

**Comment by end2endzone** [comment]
Implement a --namespace argument to allow changing the default namespace from bin2cpp to the value specified by the argument.

**Comment by end2endzone** [comment]
Implement a --help and --h to automatically print the help

**Comment by end2endzone** [comment]
Implement a --folder=value argument to add all files of a given folder.

**Comment by end2endzone** [comment]
Rename argument chunksize to bytesperrow ?

**Comment by isaacault** [comment]
I just forked, I am going to start working this. Cheers.

**Comment by end2endzone** [comment]
Hi. I am new to git and github. As far as I know, forking means that you
copied my repo to your own account so I wont benefit from your
changes/improvements. Would you prefer becoming a contributor ? If you only
want to "play with it to make it your own", that good too.

Anyway, thank for looking at my stuff!

Antoine

2017-12-15 22:27 GMT-05:00 Isaac Ault <notifications@github.com>:
