### ISSUE TITLE
Cannot compile on linux

### ISSUE THREAD

**Issue by Kirottu** [end2endzone/bin2cpp#33]
I am trying to build this software on linux, but it's giving me loads of issues.
First of all it complained about missing rapidassist cmake files, so i got the latest version of rapidassist from its repo. And then i set its path properly so bin2cpp cmake can include it but then it fails with it trying to load `rapidassist-targets.cmake` from the build/cmake directory in rapidassist root. That file seems to be nowhere to be found.

**Comment by end2endzone** [comment]
Hi. Thank you for your interest in bin2cpp. I would gladly assist you compiling the software.

You cannot compile bin2cpp and rapidassist "in one step". RapidAssist is a dependency that must be already "installed" on the system before you can build bin2cpp. The same goes for gtest which is a dependency to both bin2cpp and RapidAssist.
In other words, compile and install each library/software in the following order:

1) build and install gtest
2) build and install RapidAssist
3) build and install bin2cpp.

bin2cpp provides scripts to facilitate the building for you. The scripts can be found in [ci/travis](https://github.com/end2endzone/bin2cpp/tree/master/ci/travis) directory. There are 3 scripts, one for each step specified above: `install_googletest.sh`, `install_rapidassist.sh` and `build_library.sh`. They are designed to be executed on [Travis CI](https://travis-ci.org/github/end2endzone/bin2cpp) and requires the environment variable `TRAVIS_BUILD_DIR` to be set to the location where you cloned the bin2cpp repository or extracted the source code. Once the environment variable is set, you should be able to execute each script one by one. 

During the compilation process, dependencies (gtest and RapidAssist) will be cloned in `third_parties` directory (for example, `third_parties/googletest`) under `$TRAVIS_BUILD_DIR`. At the end of the process, bin2cpp executable will be located in the `install` directory under `$TRAVIS_BUILD_DIR`.

You can see a build example on [Travis CI bin2cpp page](https://travis-ci.org/github/end2endzone/bin2cpp).

You can also read the [INSTALL.md](https://github.com/end2endzone/bin2cpp/blob/master/INSTALL.md) file to get more details.


Try it out. If you get to compile, close the issue. If you still have issues compiling the software, I will be glad to keep helping.
Leave a star if you like bin2cpp. That is always a nice way to say thank you.

**Comment by Kirottu** [comment]
I figured I should build and install rapidassist, that should really be a step in the build instructions and i got the utility working. It is working very well too, just the thing I was looking for

**Comment by end2endzone** [comment]
I am happy that bin2cpp fits your needs.

As you suggested, I would like to take this opportunity to improve the build instructions. Could you elaborate on what you were expecting in the build documentation? I think your confusion was about the fact that software prerequisite needed to be build and installed on the system before building the project. There is a statement in the [software prerequisite section](https://github.com/end2endzone/bin2cpp/blob/master/INSTALL.md#software-requirements) that says, "_The following software must be installed on the system for compiling source code_". To be clear, I do not blame you for missing (or not understanding) this line. It is more likely that documentation is to blame.

I could change the previous line to something like _"The following software must be compiled and installed on the system before for compiling source code_". Also, I could add a step 0.5 [in the build step](https://github.com/end2endzone/bin2cpp/blob/master/INSTALL.md#build-steps) with a statement such as `Build and install all software prerequisites before building this software`. Do you think this would be clear enough and would had **prevented** your issue ?

I am also open to your suggestions. Where were you expecting in the documentation a statement that clearly states that gtest and rapidassist must be compiled and installed first?

Regards,
Antoine

**Comment by Kirottu** [comment]
Ah, I see i didn't read the install documentation well enough, but in my opinion the step of installing the prequisities would have been helpful. And yes adding a section for installing all the prequisities in the build guide would clear it up a whole lot to me, and hopefully others too.
