### ISSUE TITLE
Temp folder

### ISSUE THREAD

**Issue by hot202xu1** [end2endzone/bin2cpp#37]
Add option to save it to temp folder

**Comment by end2endzone** [comment]
Hi. Thank you for showing interest for this tool. It is much appreciated.

I do not understand what you mean, could you elaborate a little more on your expectations ?

From what I understand, you would like to be able to execute one of the following 2 scenarios:
1. Have the generated code (the .h and .cpp files) to be generated in the system "temp directory". If this is correct, then you can modify the `output` argument in the [command line example](https://github.com/end2endzone/bin2cpp/blob/2.3.0/README.md#command) with `--output=%TEMP%` (or `--output=/tmp` if you are on linux). This will tell bin2cpp to generate all files in the system "temp directory".
2. From your application that uses bin2cpp generated files, save the file in the temp directory with the `bin2cpp::File::save()` method. I do not plan to create a specialized method that would save the file in the temp directory (ie: `saveInTempDirectory()`). From my point of view, this feature would be too specific. However, you can implement such functionality inside you application. From the [code sample in the README.md file](https://github.com/end2endzone/bin2cpp/blob/2.3.0/README.md#code-sample-using-embedded-files), you can change the code as the following:
```cpp
  //Saving content back to a file with the same name in users' temp directory.
  std::string output_path = (std::getenv("TEMP") ? std::getenv("TEMP") : "");
  if (!output_path.empty())
    output_path.append("\\");
  output_path.append(resource.getFilename());
  printf("Saving embedded file to '%s'...\n", output_path.c_str());
  bool saved = resource.save(output_path.c_str());
  if (saved)
    printf("saved\n");
  else
    printf("failed\n");
```

The code above depends on the environment variable `TEMP` to be set properly, but you can also use function [GetTempPath()](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppatha) from win32 api to have

**Comment by end2endzone** [comment]
Did you have time to try the proposed solution ? Does it resolved the issue ?

**Comment by end2endzone** [comment]
I modified the README.md file and [added a section](https://github.com/end2endzone/bin2cpp#code-sample-querying-the-generated-code-1) that shows how to extract all registered files to the user's temporary directory.

I invite you to try the proposed solution. Please let me know if anything is not working as you expect. Close the issue if your problem is now resolved.
