### ISSUE TITLE
Allow generating into subfolder

### ISSUE THREAD

**Issue by MatthewScholefield** [end2endzone/bin2cpp#47]
Suppose I want to generated files in a subfolder like:
```
example
├── CMakeLists.txt
└── src
    ├── generated
    │   ├── foo-data.cpp
    │   └── foo-data.h
    └── main.cpp
```
From `main.cpp` I would want to use `#include "generated/foo-data.h"`, so I would not add `src/generated` as a compiler include directive. However, this would cause compilation of `foo-data.cpp` to error with the `#include "foo-data.h"`.

It would be nice to support generating into a subfolder where the `#include "{headerFile}"` within the `cpp` file references it.

I tried this but it didn't work:

```
dd if=/dev/urandom bs=1M count=10 of=foo-data.bin
bin2cpp --file=foo-data.bin --headerfile="generated/foo-data.h" --output=. --identifier=TorchScript
```

**Comment by end2endzone** [comment]
This is a valid use case but one that I am not expecting or used to. For example, I usually generate files out of the `src` directory, for example, in `${CMAKE_BINARY_DIR}` directory. Also, Visual Studio compiler (at least from VS2010 and above) usually add the `cpp`'s parent directory to the list of include directive. In other words, your scenario works out of the box with Visual Studio. To be clear, I still think bin2cpp should be fix/updated to support such a use case.

As a quick and dirty fix, we could change [SegmentGenerator.cpp, line 84](https://github.com/end2endzone/bin2cpp/blob/f01fd693e4f823097879a7516ec3f5b3923e7c76/src/bin2cpp/SegmentGenerator.cpp#L94) and replace `headerFilename` by `headerPath` which would result in the string `#include "./generated/foo-data.h"`. We would also have to make the same corrections in [ArrayGenerator.cpp, line 86](https://github.com/end2endzone/bin2cpp/blob/f01fd693e4f823097879a7516ec3f5b3923e7c76/src/bin2cpp/ArrayGenerator.cpp#L86), [StringGenerator.cpp, line 86](https://github.com/end2endzone/bin2cpp/blob/f01fd693e4f823097879a7516ec3f5b3923e7c76/src/bin2cpp/StringGenerator.cpp#L86) and [Win32ResourceGenerator.cpp, line 94](https://github.com/end2endzone/bin2cpp/blob/f01fd693e4f823097879a7516ec3f5b3923e7c76/src/bin2cpp/Win32ResourceGenerator.cpp#L94). 
It is not ideal but I think it would solve your issue.

If you allow more time, I might revisit the code of how I pass all arguments down to a generator instance. I think it is a bit messy and not quite intuitive. The expected and elegant solution to this problem would simply be to "paste" whatever we set for argument `--headerfile` as the input for [SegmentGenerator.cpp, line 84](https://github.com/end2endzone/bin2cpp/blob/f01fd693e4f823097879a7516ec3f5b3923e7c76/src/bin2cpp/SegmentGenerator.cpp#L94).

Let me know what you think.

**Comment by end2endzone** [comment]
Hi @MatthewScholefield. I have created branch `feature-issue47` and made corrections to support this feature. The code is now reintegrated into master. Could you validate that the feature is working as you expect. If not, could you please provide feedback and I will make the required modifications. If you feel so, you can also provided your own modifications.

If everything is working as you expect, please close the issue. I will then proceed with the release of version 2.4.0 and create a tag. I do not plan to fix the remaining issues in the current version.

**Comment by end2endzone** [comment]
Hi. It has been 2 weeks now and I would like to release version 2.4.0 and create a tag. No offence, but I feel uncomfortable having the documentation update about downloadable binaries without having a tag to make them available. Now that binaries are available, I would like to make them usable and allow users to download them instead of building the software. There are also 14 issues resolved since the previous release and I do not want to wait too much and have a lot of changes between releases.

From my point of view, and assuming that I understood your problem correctly, the issue has been resolved. Like I said, if you feel that I am wrong, feel free to open the issue again. I will create the tag tonight or tomorrow.
