### ISSUE TITLE
Split one output C/C++ file into multiple ~100KB chunks, to make a file feasible to compile.

### ISSUE THREAD

**Issue by HackerDaGreat57** [end2endzone/bin2cpp#65]
Sorry to bug you again.

The title has it all.

Thanks in advance.

**Comment by end2endzone** [comment]
I do not understand what you mean. I do not understand why you would need to split a generated file. [This test](https://github.com/end2endzone/bin2cpp/blob/df91013c68b4560272503892cea7e38dc3c5d213/test/bin2cpp_unittest/TestExtraction.cpp#L303) shows that files up to 10 megabytes can be compiled without a problem, on all platforms.

Assuming that splitting would be required, how do you expect the whole thing to work? I do not know if there would be away to "join" the data from multiple source files as one consecutive stream.

Could you elaborate on what you are expecting?

**Comment by HackerDaGreat57** [comment]
I mean that if I have some sort of binary file that I would write to disk from my app, the *.cpp file for that would usually be several gigabytes long. I tried compiling it overnight, turns out my SSD got full of swap mem and had to reboot my computer (Windows 11 if it helps).

Do header files get compiled seperately (compile one, write object, do another header, etc, finally link) or all at once (compile all, write all objects AFTER compiling all, link)?

After typing all of this up and realizing what I'm doing is crazy and I'm gonna switch to a 64GB mem Mac soon:
Nevermind. Sorry for the trouble, I'm just crazy about breaking limits even if I'm doing something pointless.
